version: 2.1
executors:
  node:
    docker:
      - image: cimg/node:12.13.0
    working_directory: ~/repo
    resource_class: small
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run: npm test

workflows:
  version: 2

  build-and-test:
    jobs:
      - build
